# type: ignore
# -*- coding: utf-8 -*-
#
# Chinese Language RTD & Sphinx config file
#
# Uses ../conf_common.py for most non-language-specific settings.
# Importing conf_common adds all the non-language-specific
# parts to this conf module
try:
    from conf_common import *  # noqa: F403,F401
except ImportError:
    import os
    import sys

    sys.path.insert(0, os.path.abspath(".."))
    from conf_common import *  # noqa: F403,F401

import datetime

current_year = datetime.datetime.now().year

# General information about the project.
project = "您的项目文档"
copyright = "2016 - {}，您的公司名称".format(current_year)  # noqa: A001

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "zh_CN"

html_zip = f"your-project-{language}-{release}"  # noqa: F405

# The chatbot is able to answer only about the latest documentation.
# Enable Documentation Chatbot widget only for the latest version.
# if release == 'latest':
#    html_js_files = html_js_files + ['js/chatbot_widget_cn.js']  # noqa: F405

# HTML search options for Chinese
# Configure Chinese language search to use proper stemmer
html_search_options = {"type": "default"}


def setup(app):
    """Sphinx setup function for Chinese documentation."""
    # Call the common setup function to register link_to_translation role
    from conf_common import setup as common_setup

    common_setup(app)

    # Add custom Chinese query splitter with late priority to ensure it loads
    # after searchtools.js and can override the default splitQuery function
    app.add_js_file("js/chinese_splitter.js", priority=999)
